# Generated by Django 6.0.4 on 2026-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('tech', 'Technology / IT'), ('finance', 'Finance / Banking'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail / E-commerce'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('hospitality', 'Hospitality / Travel'), ('media', 'Media / Entertainment'), ('government', 'Government / Public sector'), ('nonprofit', 'Non-profit'), ('other', 'Other')], default='', max_length=32),
        ),
    ]
